=== ODD-Senior-Design/API/test/sample_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "PatientsSchema": {
            "properties": {
                "id": {
                    "title": "id",
                    "type": "string",
                    "format": "uuid",
                    "readOnly": true
                },
                "first_name": {
                    "title": "first_name",
                    "type": "string",
                    "$provider": "faker.first_name"
                },
                "last_name": {
                    "title": "last_name",
                    "type": "string",
                    "$provider": "faker.last_name"
                },
                "dob": {
                    "title": "dob",
                    "type": "string",
                    "format": "date",
                    "$provider": "faker.date"
                }
            },
            "type": "object",
            "required": [
                "id",
                "first_name",
                "last_name",
                "dob"
            ],
            "additionalProperties": false
        },
        "ImageSetsSchema": {
            "properties": {
                "id": {
                    "title": "id",
                    "type": "string",
                    "format": "uuid",
                    "readOnly": true
                },
                "patient_id": {
                    "title": "patient_id",
                    "type": "string",
                    "format": "uuid"
                },
                "patient": {
                    "$ref": "#/definitions/PatientsSchema"
                }
            },
            "type": "object",
            "required": [
                "id",
                "patient_id",
                "patient"
                ],
            "additionalProperties": false
        },
        "ImagesSchema": {
            "properties": {
                "id": {
                    "title": "id",
                    "type": "string",
                    "format": "uuid",
                    "readOnly": true
                },
                "set_id": {
                    "title": "image_set_id",
                    "type": "string",
                    "format": "uuid"
                },
                "patient_id": {
                    "title": "patient_id",
                    "type": "string",
                    "format": "uuid"
                },
                "image_set": {
                    "$ref": "#/definitions/ImageSetsSchema"                    
                },
                "image_timestamp": {
                    "title": "image_timestamp",
                    "type": "string",
                    "format": "date-time"
                },
                "uri": {
                    "title": "image_uri",
                    "type": "string",
                    "$provider": "faker.image_url"
                }
            },
            "type": "object",
            "required": [
                "id",
                "set_id",
                "patient_id",
                "image_set",
                "image_timestamp",
                "uri"
            ],
            "additionalProperties": false
        },
        "AssessmentsSchema": {
            "properties": {
                "id": {
                    "title": "id",
                    "type": "string",
                    "format": "uuid",
                    "readOnly": true
                },
                "image_id": {
                    "title": "image_id",
                    "type": "string",
                    "format": "uuid"
                },
                "set_id": {
                    "title": "set_id",
                    "type": "string",
                    "format": "uuid"
                },
                "patient_id": {
                    "title": "patient_id",
                    "type": "string",
                    "format": "uuid"
                },
                "image": {
                    "$ref": "#/definitions/ImagesSchema"

                },
                "assessment_timestamp": {
                    "title": "assessment_timestamp",
                    "type": "string",
                    "format": "date-time"
                },
                "assessment": {
                    "title": "assessment",
                    "type": "boolean"
                }
            },
            "type": "object",
            "required": [
                "id",
                "image_id",
                "set_id",
                "patient_id",
                "image",
                "assessment_timestamp",
                "assessment"
            ],
            "additionalProperties": false
        }
    },
    "type": "object",
    "properties": {
        "patients": {
            "title": "patients",
            "type": "array",
            "items": {
                "$ref": "#/definitions/PatientsSchema"
            },
            "minItems": 1
        },
        "image_sets": {
            "title": "image_sets",
            "type": "array",
            "items": {
                "$ref": "#/definitions/ImageSetsSchema"
            },
            "minItems": 1
        },
        "images": {
            "title": "images",
            "type": "array",
            "items": {
                "$ref": "#/definitions/ImagesSchema"
            },
            "minItems": 1
        },
        "assessments": {
            "title": "assessments",
            "type": "array",
            "items": {
                "$ref": "#/definitions/AssessmentsSchema"
            },
            "minItems": 1
        }
    },
    "required": [
        "patients",
        "image_sets",
        "images",
        "assessments"
    ],
    "additionalProperties": false
}

=== ODD-Senior-Design/API/test/fake_data.json
{
    "patients": [
        {
            "id": "36b0b2ac-4c41-4031-aa9c-45cb5fa1f31a",
            "first_name": "Gregory",
            "last_name": "Esparza",
            "dob": "2006-08-01"
        },
        {
            "id": "6551d1eb-cf30-454e-8720-ffcc996b29da",
            "first_name": "Joseph",
            "last_name": "Smith",
            "dob": "1995-06-20"
        },
        {
            "id": "131c59c5-7b73-45e5-9374-176cc7a0fd79",
            "first_name": "Donald",
            "last_name": "Flores",
            "dob": "2001-06-25"
        },
        {
            "id": "4ddd9f3c-7c52-4713-9e25-31cafeb2beb3",
            "first_name": "Philip",
            "last_name": "Pacheco",
            "dob": "2021-01-15"
        }
    ],
    "image_sets": [
        {
            "id": "eaf09650-210a-4cb8-8653-aa97461b338d",
            "patient_id": "9f3f7241-41d2-4d19-8ad3-42579faaba13",
            "patient": {
                "id": "9f3f7241-41d2-4d19-8ad3-42579faaba13",
                "first_name": "Wendy",
                "last_name": "Moore",
                "dob": "1984-03-07"
            }
        },
        {
            "id": "34dbb3ae-0c0e-4b94-a473-022030cefcf2",
            "patient_id": "baeddda5-2f24-466f-a669-fd4ab5b11354",
            "patient": {
                "id": "baeddda5-2f24-466f-a669-fd4ab5b11354",
                "first_name": "Christina",
                "last_name": "Hahn",
                "dob": "2008-05-10"
            }
        },
        {
            "id": "49799f1e-6d6e-4e1b-92bf-f1bdb3f17896",
            "patient_id": "b177a462-b9be-4caf-a2a3-190b4e641118",
            "patient": {
                "id": "b177a462-b9be-4caf-a2a3-190b4e641118",
                "first_name": "Andrew",
                "last_name": "Ashley",
                "dob": "1972-09-15"
            }
        },
        {
            "id": "9eed1614-48e4-4307-b9b4-e894eea41c1e",
            "patient_id": "28b48dda-1a36-41b0-a97d-80f6d57109bd",
            "patient": {
                "id": "28b48dda-1a36-41b0-a97d-80f6d57109bd",
                "first_name": "Nicholas",
                "last_name": "Garcia",
                "dob": "2010-10-05"
            }
        }
    ],
    "images": [
        {
            "id": "6a94274c-a571-4e76-8802-b2746631e758",
            "set_id": "fe24cbbc-e6a8-400c-ba5e-412bf9f59c92",
            "patient_id": "9a11e133-e1b5-4e7c-b648-1eec675db56f",
            "image_set": {
                "id": "fe24cbbc-e6a8-400c-ba5e-412bf9f59c92",
                "patient_id": "9a11e133-e1b5-4e7c-b648-1eec675db56f",
                "patient": {
                    "id": "9a11e133-e1b5-4e7c-b648-1eec675db56f",
                    "first_name": "Eileen",
                    "last_name": "Diaz",
                    "dob": "1976-02-29"
                }
            },
            "image_timestamp": "1976-07-17T01:37:58.916115+00:00",
            "uri": "https://dummyimage.com/457x885"
        },
        {
            "id": "a809fb57-ae86-4e1a-aea6-f2a1932f271a",
            "set_id": "effdd79d-c212-4206-8732-c953f1596b74",
            "patient_id": "8ae60e3f-16c9-4c4b-be07-26ed64d20a25",
            "image_set": {
                "id": "effdd79d-c212-4206-8732-c953f1596b74",
                "patient_id": "8ae60e3f-16c9-4c4b-be07-26ed64d20a25",
                "patient": {
                    "id": "8ae60e3f-16c9-4c4b-be07-26ed64d20a25",
                    "first_name": "Katherine",
                    "last_name": "Myers",
                    "dob": "2011-09-20"
                }
            },
            "image_timestamp": "2011-11-30T10:15:57.293291+00:00",
            "uri": "https://dummyimage.com/355x324"
        },
        {
            "id": "ef1c8eae-8072-47be-9faa-d0a81bbf472b",
            "set_id": "2344c008-8acc-4e5e-ac04-e4f2fe658f80",
            "patient_id": "57a1e8d1-aebe-4cd6-9250-82696ce9361f",
            "image_set": {
                "id": "2344c008-8acc-4e5e-ac04-e4f2fe658f80",
                "patient_id": "57a1e8d1-aebe-4cd6-9250-82696ce9361f",
                "patient": {
                    "id": "57a1e8d1-aebe-4cd6-9250-82696ce9361f",
                    "first_name": "Jennifer",
                    "last_name": "Roberts",
                    "dob": "2022-10-15"
                }
            },
            "image_timestamp": "1972-09-12T00:02:57.791273+00:00",
            "uri": "https://picsum.photos/900/303"
        },
        {
            "id": "04fa2c51-1639-41c0-b49a-7c4dba5b7256",
            "set_id": "c9fcda96-16d9-42b4-9326-7d794f8f2317",
            "patient_id": "6985affd-bae9-402c-90aa-50b3fc69e5ae",
            "image_set": {
                "id": "c9fcda96-16d9-42b4-9326-7d794f8f2317",
                "patient_id": "6985affd-bae9-402c-90aa-50b3fc69e5ae",
                "patient": {
                    "id": "6985affd-bae9-402c-90aa-50b3fc69e5ae",
                    "first_name": "Larry",
                    "last_name": "Gibbs",
                    "dob": "1981-11-20"
                }
            },
            "image_timestamp": "2014-02-22T19:16:53.408912+00:00",
            "uri": "https://placekitten.com/396/319"
        }
    ],
    "assessments": [
        {
            "id": "da813014-0576-4d42-8cc0-9104cc904561",
            "image_id": "344b7dd1-1b0f-4617-871e-2def5741e8a1",
            "set_id": "346b4323-e4ad-4235-bc08-15dcc02ddb85",
            "patient_id": "506daccb-bdd5-4c8a-9f1f-384662b16c26",
            "image": {
                "id": "344b7dd1-1b0f-4617-871e-2def5741e8a1",
                "set_id": "346b4323-e4ad-4235-bc08-15dcc02ddb85",
                "patient_id": "506daccb-bdd5-4c8a-9f1f-384662b16c26",
                "image_set": {
                    "id": "346b4323-e4ad-4235-bc08-15dcc02ddb85",
                    "patient_id": "506daccb-bdd5-4c8a-9f1f-384662b16c26",
                    "patient": {
                        "id": "506daccb-bdd5-4c8a-9f1f-384662b16c26",
                        "first_name": "Carla",
                        "last_name": "West",
                        "dob": "1975-08-16"
                    }
                },
                "image_timestamp": "1996-09-08T15:57:21.608459+00:00",
                "uri": "https://placekitten.com/64/306"
            },
            "assessment_timestamp": "1995-10-04T19:38:52.559248+00:00",
            "assessment": false
        },
        {
            "id": "08de568a-a783-431a-b8b6-d14c77a68822",
            "image_id": "e7c845da-c70c-4ce6-b7af-145741b37c41",
            "set_id": "1b33f5c9-b2a6-4c28-902d-db3dc5bde2ae",
            "patient_id": "49fefb15-4b8a-4f8c-9609-2459381428b6",
            "image": {
                "id": "e7c845da-c70c-4ce6-b7af-145741b37c41",
                "set_id": "1b33f5c9-b2a6-4c28-902d-db3dc5bde2ae",
                "patient_id": "49fefb15-4b8a-4f8c-9609-2459381428b6",
                "image_set": {
                    "id": "1b33f5c9-b2a6-4c28-902d-db3dc5bde2ae",
                    "patient_id": "49fefb15-4b8a-4f8c-9609-2459381428b6",
                    "patient": {
                        "id": "49fefb15-4b8a-4f8c-9609-2459381428b6",
                        "first_name": "Mariah",
                        "last_name": "Lewis",
                        "dob": "1984-06-22"
                    }
                },
                "image_timestamp": "2001-01-25T13:15:56.066496+00:00",
                "uri": "https://placekitten.com/380/157"
            },
            "assessment_timestamp": "1988-08-09T05:52:42.676214+00:00",
            "assessment": true
        },
        {
            "id": "4b106b2c-a777-4298-a83c-60ad401d5500",
            "image_id": "59f77ac2-0238-4b11-ab4c-f3bdcd211b7e",
            "set_id": "8ad66c74-e100-4562-ab03-4a13422b8a1c",
            "patient_id": "4c0f57bf-6891-437b-81b6-81183f03bc94",
            "image": {
                "id": "59f77ac2-0238-4b11-ab4c-f3bdcd211b7e",
                "set_id": "8ad66c74-e100-4562-ab03-4a13422b8a1c",
                "patient_id": "4c0f57bf-6891-437b-81b6-81183f03bc94",
                "image_set": {
                    "id": "8ad66c74-e100-4562-ab03-4a13422b8a1c",
                    "patient_id": "4c0f57bf-6891-437b-81b6-81183f03bc94",
                    "patient": {
                        "id": "4c0f57bf-6891-437b-81b6-81183f03bc94",
                        "first_name": "Ryan",
                        "last_name": "Gibson",
                        "dob": "1990-05-25"
                    }
                },
                "image_timestamp": "2018-04-08T19:06:38.820504+00:00",
                "uri": "https://placekitten.com/882/626"
            },
            "assessment_timestamp": "1976-01-25T09:58:38.704674+00:00",
            "assessment": false
        },
        {
            "id": "c7a3a9fc-3d96-4610-8e1b-94505a814b8a",
            "image_id": "b075ea10-f6e2-49ab-bac1-a2c33663745d",
            "set_id": "40db9882-57f6-48be-9a0c-aba14164029b",
            "patient_id": "bc40662f-ee5e-44bf-9b7d-6f2529085eff",
            "image": {
                "id": "b075ea10-f6e2-49ab-bac1-a2c33663745d",
                "set_id": "40db9882-57f6-48be-9a0c-aba14164029b",
                "patient_id": "bc40662f-ee5e-44bf-9b7d-6f2529085eff",
                "image_set": {
                    "id": "40db9882-57f6-48be-9a0c-aba14164029b",
                    "patient_id": "bc40662f-ee5e-44bf-9b7d-6f2529085eff",
                    "patient": {
                        "id": "bc40662f-ee5e-44bf-9b7d-6f2529085eff",
                        "first_name": "Nicole",
                        "last_name": "Smith",
                        "dob": "2022-03-07"
                    }
                },
                "image_timestamp": "1982-05-07T13:53:31.277565+00:00",
                "uri": "https://dummyimage.com/562x74"
            },
            "assessment_timestamp": "1984-10-11T22:03:53.629902+00:00",
            "assessment": false
        }
    ]
}
